use alloy_primitives::{keccak256, Address, B256, U256};
use alloy_rlp::{BufMut, Encodable, Header};
use k256::ecdsa::{RecoveryId, Signature, SigningKey};
use thiserror::Error;
use zeroize::Zeroizing;

/// EIP-1559 transaction signing.
///
/// Written by hand rather than pulled from a provider stack, because the only
/// thing needed here is these bytes and adding a whole abstraction to get them
/// would cost more than it explains. Being subtly wrong here does not produce a
/// failure: it produces a valid transaction that spends gas and does something
/// other than what was intended, so the tests hold it to bytes generated
/// independently by viem rather than to my reading of the spec.
#[derive(Debug, Error)]
pub enum SignError {
    #[error("the private key is not a valid signing key")]
    BadKey,
    #[error("signing failed")]
    Failed,
}

#[derive(Debug, Clone)]
pub struct Eip1559 {
    pub chain_id: u64,
    pub nonce: u64,
    pub max_priority_fee_per_gas: u128,
    pub max_fee_per_gas: u128,
    pub gas_limit: u64,
    pub to: Address,
    pub value: u128,
    pub data: Vec<u8>,
}

/// The transaction type byte that prefixes the RLP payload.
const TX_TYPE_EIP1559: u8 = 0x02;

impl Eip1559 {
    /// The nine field payload that gets signed. The access list is always an
    /// empty list: nothing here benefits from one, and an absent field is not
    /// the same as an empty one.
    fn encode_payload(&self, out: &mut dyn BufMut, signature: Option<(u8, U256, U256)>) {
        let mut fields: Vec<u8> = Vec::new();
        self.chain_id.encode(&mut fields);
        self.nonce.encode(&mut fields);
        self.max_priority_fee_per_gas.encode(&mut fields);
        self.max_fee_per_gas.encode(&mut fields);
        self.gas_limit.encode(&mut fields);
        self.to.encode(&mut fields);
        self.value.encode(&mut fields);
        self.data.as_slice().encode(&mut fields);
        // Empty access list.
        Header {
            list: true,
            payload_length: 0,
        }
        .encode(&mut fields);

        if let Some((y_parity, r, s)) = signature {
            y_parity.encode(&mut fields);
            r.encode(&mut fields);
            s.encode(&mut fields);
        }

        Header {
            list: true,
            payload_length: fields.len(),
        }
        .encode(out);
        out.put_slice(&fields);
    }

    /// The bytes that are hashed to produce the signing hash: the type byte
    /// followed by the unsigned payload.
    #[must_use]
    pub fn unsigned(&self) -> Vec<u8> {
        let mut out = vec![TX_TYPE_EIP1559];
        self.encode_payload(&mut out, None);
        out
    }

    #[must_use]
    pub fn signing_hash(&self) -> B256 {
        keccak256(self.unsigned())
    }

    /// Signs and returns the raw transaction ready for `eth_sendRawTransaction`,
    /// alongside the hash it will have on chain.
    ///
    /// The hash is computed locally rather than trusted from whatever an
    /// endpoint answers, so a node that returns a different one can be caught
    /// lying rather than believed.
    pub fn sign(&self, secret: &Zeroizing<[u8; 32]>) -> Result<Signed, SignError> {
        let key = SigningKey::from_slice(&secret[..]).map_err(|_| SignError::BadKey)?;
        let (signature, recovery): (Signature, RecoveryId) = key
            .sign_prehash_recoverable(self.signing_hash().as_slice())
            .map_err(|_| SignError::Failed)?;

        // Low-s is enforced by k256's normalisation, which matters because a
        // high-s signature is malleable and some nodes refuse it outright.
        let r = U256::from_be_slice(&signature.r().to_bytes());
        let s = U256::from_be_slice(&signature.s().to_bytes());

        let mut raw = vec![TX_TYPE_EIP1559];
        self.encode_payload(&mut raw, Some((u8::from(recovery.is_y_odd()), r, s)));

        Ok(Signed {
            hash: keccak256(&raw),
            raw,
        })
    }
}

#[derive(Debug, Clone)]
pub struct Signed {
    pub raw: Vec<u8>,
    pub hash: B256,
}

impl Signed {
    #[must_use]
    pub fn raw_hex(&self) -> String {
        format!("0x{}", hex::encode(&self.raw))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generated by `scripts/sign-vector.ts`, which signs the identical
    /// transaction with viem. Two independent implementations agreeing byte for
    /// byte is worth far more than either one agreeing with my reading of the
    /// spec.
    const KEY: [u8; 32] = [
        0xac, 0x09, 0x74, 0xbe, 0xc3, 0x9a, 0x17, 0xe3, 0x6b, 0xa4, 0xa6, 0xb4, 0xd2, 0x38, 0xff,
        0x94, 0x4b, 0xac, 0xb4, 0x78, 0xcb, 0xed, 0x5e, 0xfc, 0xae, 0x78, 0x4d, 0x7b, 0xf4, 0xf2,
        0xff, 0x80,
    ];

    const UNSIGNED: &str = "0x02f8ab821237078084026920608304e2009400005ea00ac477b1030ce78506496e8c2de24bf580b884161ac21f00000000000000000000000020d7cada668d1fd24ddf905cb79069934a77309d0000000000000000000000000000a26b00c1f0df003000390027140000faa71900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c0";
    const SIGNING_HASH: &str = "0x74d5253a282575be46a3def5469f123980b0b4678497c7023340a7675f1498ce";
    const SIGNED: &str = "0x02f8ee821237078084026920608304e2009400005ea00ac477b1030ce78506496e8c2de24bf580b884161ac21f00000000000000000000000020d7cada668d1fd24ddf905cb79069934a77309d0000000000000000000000000000a26b00c1f0df003000390027140000faa71900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001c001a0b5477696b23b3eac3db8dd7e4cefd46c216af31a0776bd3420ff3a29d97306b0a006d62fe0f6e3c41b59056cb0144dcc6194264c11b90824c789e4f5c29ee89f1b";
    const TX_HASH: &str = "0x2c4ed7be1cf5928829922375d071e8cf8213014053f1ab9422a967c3f7159c86";

    fn vector_tx() -> Eip1559 {
        let data = hex::decode(
            "161ac21f\
             00000000000000000000000020d7cada668d1fd24ddf905cb79069934a77309d\
             0000000000000000000000000000a26b00c1f0df003000390027140000faa719\
             0000000000000000000000000000000000000000000000000000000000000000\
             0000000000000000000000000000000000000000000000000000000000000001",
        )
        .unwrap();
        Eip1559 {
            chain_id: 4663,
            nonce: 7,
            max_priority_fee_per_gas: 0,
            max_fee_per_gas: 40_444_000,
            gas_limit: 320_000,
            to: "0x00005EA00Ac477B1030CE78506496e8C2dE24bf5"
                .parse()
                .unwrap(),
            value: 0,
            data,
        }
    }

    #[test]
    fn the_unsigned_encoding_matches_viem_byte_for_byte() {
        assert_eq!(
            format!("0x{}", hex::encode(vector_tx().unsigned())),
            UNSIGNED
        );
    }

    #[test]
    fn the_signing_hash_matches_viem() {
        assert_eq!(format!("{:?}", vector_tx().signing_hash()), SIGNING_HASH);
    }

    /// The one that matters. If these bytes differ from viem's, the transaction
    /// that reaches the sequencer is not the one anybody intended.
    #[test]
    fn the_signed_transaction_matches_viem_byte_for_byte() {
        let signed = vector_tx().sign(&Zeroizing::new(KEY)).unwrap();
        assert_eq!(signed.raw_hex(), SIGNED);
    }

    /// The hash is computed locally so a node returning a different one can be
    /// caught lying rather than believed.
    #[test]
    fn the_transaction_hash_matches_viem() {
        let signed = vector_tx().sign(&Zeroizing::new(KEY)).unwrap();
        assert_eq!(format!("{:?}", signed.hash), TX_HASH);
    }

    /// secp256k1 signing is deterministic under RFC 6979, so the same
    /// transaction and key must always produce the same bytes.
    #[test]
    fn signing_is_deterministic() {
        let a = vector_tx().sign(&Zeroizing::new(KEY)).unwrap();
        let b = vector_tx().sign(&Zeroizing::new(KEY)).unwrap();
        assert_eq!(a.raw_hex(), b.raw_hex());
    }

    #[test]
    fn a_different_nonce_produces_a_different_transaction() {
        let mut other = vector_tx();
        other.nonce = 8;
        let a = vector_tx().sign(&Zeroizing::new(KEY)).unwrap();
        let b = other.sign(&Zeroizing::new(KEY)).unwrap();
        assert_ne!(a.hash, b.hash);
    }

    #[test]
    fn refuses_a_key_that_is_not_one() {
        assert!(matches!(
            vector_tx().sign(&Zeroizing::new([0u8; 32])),
            Err(SignError::BadKey)
        ));
    }
}
